{
  "properties" : { },
  "id" : "a0379bcdfce341beb70a22c4b50be63c",
  "script" : null,
  "groupId" : "3d73e9ac40514a28b2e4511c59d208d9",
  "name" : "未定义名称",
  "createTime" : 1729563379368,
  "updateTime" : null,
  "lock" : null,
  "createBy" : "admin",
  "updateBy" : null,
  "path" : "/hello",
  "method" : "GET",
  "parameters" : [ ],
  "options" : [ ],
  "requestBody" : null,
  "headers" : [ ],
  "paths" : [ ],
  "responseBody" : null,
  "description" : null,
  "requestBodyDefinition" : null,
  "responseBodyDefinition" : null
}
================================
return 'Hello magic-api'